version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    depends_on:
      - startup
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=Docker

  cassandra:
    image: cassandra:latest
    container_name: cassandra_db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra_data:/var/lib/cassandra
    restart: unless-stopped

  startup:
      image: cassandra:4
      depends_on:
        - cassandra
      restart: "no"
      entrypoint: ["/startup.sh"]
      volumes:
        - ./startup.sh:/startup.sh

volumes:
  cassandra_data:
